# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='todolist',
            name='task_in_history',
            field=models.BooleanField(default=False),
        ),
    ]
