# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interpoint', '0002_auto_20170413_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='task_status',
            new_name='task_is_completed',
        ),
    ]
